### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by McMistrzYT** [mileszim/tempmail.js#110]
![image](https://user-images.githubusercontent.com/56406996/111437175-157b8400-8703-11eb-9291-05dafe4ba683.png)

Any help? This is my code:
![image](https://user-images.githubusercontent.com/56406996/111437226-23c9a000-8703-11eb-8998-40a77e707ce0.png)

**Comment by mileszim** [comment]
I'm gonna wager since the repo has not been updated in 3 years, the babel transpiler is broke. TBH a lot of the code should be re-written with modern standards. Always open to PRs! I myself probably wont update this in the time you want, so perhaps check out if any of the forks are good?

**Comment by McMistrzYT** [comment]
Yeah, good idea. Thanks.
