### ISSUE TITLE
Implementing a polling method

### ISSUE THREAD

**Issue by giacomocerquone** [mileszim/tempmail.js#3]
Everytime I use this module for testing purposes I find myself writing a very ugly recursive-setTimeout function to wait for a particular email. Do you think it'd be a good idea to implement it directly inside the module? I can do a PR if you want it.

**Comment by mileszim** [comment]
If you could submit a PR that would be fantastic, I'd like to see in more detail the challenge you face here

**Comment by giacomocerquone** [comment]
I already have an idea on how to implement this feature but I'll write some code after wednesday eight.

**Comment by giacomocerquone** [comment]
@mileszim any news?

**Comment by mileszim** [comment]
@giacomocerquone I believe this is fixed here https://github.com/mileszim/tempmail.js/blob/master/src/index.js#L76-L89 lemme know id you have issues.
