### ISSUE TITLE
Actual providers don't work

### ISSUE THREAD

**Issue by giacomocerquone** [mileszim/tempmail.js#4]
When I started using this module things were not working because the providers you included are not working. Right now everything's fine using "leeching.net" as a provider.

**Comment by mileszim** [comment]
seems like they are constantly switching providers, so it would be good to have a method that fetches the current providers and uses those instead of having to constantly update the hardcoded ones here. do you mind submitting a PR for this as well?

**Comment by mileszim** [comment]
closed in favor of #28
