### ISSUE TITLE
No message is formatting because messages is a promise and not an array

### ISSUE THREAD

**Issue by giacomocerquone** [mileszim/tempmail.js#9]
https://github.com/mileszim/tempmail.js/blob/master/src/index.js#L29

In this line you use messages like if it would be an array, but actually, reading the Fetch.API documentation, it returns a promise.
This is the same reason why I've added `await` here: https://github.com/giacomocerquone/tempmail.js/blob/30ea1def1de094757d35cfda35e2f79d06c31f3b/src/utils.js#L36

The fixes is arriving ;)

(I'm going to change the messages[0] to messages.length due to idiomaticjs https://github.com/rwaldron/idiomatic.js/#cond)

**Comment by mileszim** [comment]
Fixed by #27
